spring:
  application:
    name: jp-capacitacao-2026

  datasource:
    url: ${URL_DB:jdbc:oracle:thin:@localhost:1521:xe}
    username: ${USERNAME_DB:admin}
    password: ${PASSWORD_DB:admin}
    driver-class-name: oracle.jdbc.OracleDriver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080